### ISSUE TITLE
Upload an Ntropy logo

### ISSUE THREAD

**Issue by dmitrizagidulin** [ntropy-network/life-server#31]
For use with testnet hosting site, etc.

**Comment by narecodes** [comment]
![n-logo 2](https://user-images.githubusercontent.com/41440897/43474541-2106cec2-94eb-11e8-99a5-7f6c7c2ea201.png)

**Comment by narecodes** [comment]
![n-logo 1](https://user-images.githubusercontent.com/41440897/43474583-3a985a90-94eb-11e8-9d75-855410f34685.png)

**Comment by narecodes** [comment]
[favicon_package_v0.16.zip](https://github.com/ntropy-network/life-server/files/2254057/favicon_package_v0.16.zip)

**Comment by narecodes** [comment]
you have the SVG now and the favicon package

**Comment by dmitrizagidulin** [comment]
Cropped .png:
![n](https://user-images.githubusercontent.com/947005/43907989-d061c43c-9bc4-11e8-873f-6772ddbb442b.png)
